# Generated by Django 5.1.15 on 2026-05-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampFiche',
            fields=[
                ('id_champ', models.AutoField(primary_key=True, serialize=False)),
                ('id_version', models.IntegerField()),
                ('libelle', models.CharField(max_length=255)),
                ('type_champ', models.CharField(choices=[('texte', 'Texte'), ('nombre', 'Nombre'), ('date', 'Date'), ('booleen', 'Booléen'), ('liste', 'Liste')], max_length=20)),
                ('valeur', models.TextField(blank=True, null=True)),
                ('est_obligatoire', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=1)),
                ('id_champ_template', models.IntegerField(blank=True, null=True)),
                ('valeur_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'champ_fiche',
                'ordering': ['ordre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChampTemplate',
            fields=[
                ('id_champ_template', models.AutoField(primary_key=True, serialize=False)),
                ('id_section_template', models.IntegerField()),
                ('libelle', models.CharField(max_length=255)),
                ('type_champ', models.CharField(choices=[('text', 'Texte'), ('nombre', 'Nombre'), ('date', 'Date'), ('booleen', 'Booléen'), ('checklist', 'Checklist'), ('liste', 'Liste'), ('tableau', 'Tableau')], max_length=20)),
                ('configuration', models.JSONField(default=dict)),
                ('est_obligatoire', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('aide', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=1)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'champ_template',
                'ordering': ['ordre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColonneTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_champ', models.IntegerField()),
                ('cle', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=200)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('ordre', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'colonne_template',
                'ordering': ['ordre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Norme',
            fields=[
                ('id_norme', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'norme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OptionChamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_champ', models.IntegerField()),
                ('valeur', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'option_champ',
                'ordering': ['ordre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessusLiaison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_processus_amont', models.IntegerField()),
                ('id_processus_aval', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processus_liaison',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionTemplate',
            fields=[
                ('id_section_template', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=1)),
                ('est_actif', models.BooleanField(default=True)),
                ('id_norme', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'section_template',
                'ordering': ['ordre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatutFiche',
            fields=[
                ('id_statut', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255, unique=True)),
                ('ordre', models.IntegerField()),
                ('couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('est_final', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'statut_fiche',
                'ordering': ['ordre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VersionFiche',
            fields=[
                ('id_version', models.AutoField(primary_key=True, serialize=False)),
                ('id_processus', models.IntegerField()),
                ('statut', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Soumise', 'Soumise'), ('En_revision', 'En révision'), ('Publiee', 'Publiée'), ('Archivee', 'Archivée')], default='Brouillon', max_length=20)),
                ('id_redacteur', models.IntegerField()),
                ('numero_version', models.CharField(max_length=50)),
                ('commentaire_version', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_modif', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('id_processus_amont', models.IntegerField(blank=True, null=True)),
                ('id_processus_aval', models.IntegerField(blank=True, null=True)),
                ('revue', models.BooleanField(default=False)),
                ('commit', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'version_fiche',
                'managed': False,
            },
        ),
    ]
