# Generated by Django 5.1.4 on 2026-05-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processus',
            fields=[
                ('id_processus', models.AutoField(primary_key=True, serialize=False)),
                ('code_process', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_process', models.CharField(choices=[('Management', 'Management'), ('Realisation', 'Réalisation'), ('Support', 'Support')], max_length=20)),
                ('id_departement', models.IntegerField()),
                ('id_pilote', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processus',
                'ordering': ['nom'],
                'managed': False,
            },
        ),
    ]
