MATURITY_ARTICLES = [
    {
        "code": "a4",
        "label": "§4",
        "full_title": "§4 - Contexte",
        "weight": 15,
        "position": 4,
        "requirements": [
            {"reference": "4.1-1", "text": "Enjeux externes identifies (MESRS, reformes LMD, RNAQES)."},
            {"reference": "4.1-2", "text": "Enjeux internes identifies (organigramme 2018, maturite, RH, infrastructure)."},
            {"reference": "4.2-1", "text": "Parties interessees identifiees (etudiants, MESRS, entreprises, labos LMCS/LCSI)."},
            {"reference": "4.2-2", "text": "Besoins et attentes des parties interessees documentes."},
            {"reference": "4.3-1", "text": "Perimetre du SMQ defini et documente (licence, master, doctorat et support)."},
            {"reference": "4.4-1", "text": "Tous les processus ESI sont listes (management, realisation, support)."},
            {"reference": "4.4-2", "text": "Inputs, outputs et responsables definis pour chaque processus."},
            {"reference": "4.4-3", "text": "Matrice des interactions entre processus produite."},
        ],
    },
    {
        "code": "a5",
        "label": "§5",
        "full_title": "§5 - Leadership",
        "weight": 10,
        "position": 5,
        "requirements": [
            {"reference": "5.1-1", "text": "Engagement visible de la Direction dans la demarche qualite."},
            {"reference": "5.1-2", "text": "Politique qualite definie et coherente avec la strategie ESI."},
            {"reference": "5.2-1", "text": "Politique qualite documentee, approuvee et diffusee."},
            {"reference": "5.3-1", "text": "CAQ officiellement constituee avec membres identifies."},
            {"reference": "5.3-2", "text": "Un pilote est designe formellement par processus ESI."},
            {"reference": "5.3-3", "text": "Responsabilites des auditeurs internes definies."},
        ],
    },
    {
        "code": "a6",
        "label": "§6",
        "full_title": "§6 - Planification",
        "weight": 15,
        "position": 6,
        "requirements": [
            {"reference": "6.1-1", "text": "Risques identifies et evalues pour chaque processus."},
            {"reference": "6.1-2", "text": "Plans de traitement definis pour les risques critiques."},
            {"reference": "6.1-3", "text": "Opportunites identifiees (partenariats, labellisation, appels a projets)."},
            {"reference": "6.2-1", "text": "Objectifs qualite mesurables definis par processus."},
            {"reference": "6.2-2", "text": "Chaque objectif est lie a un KPI avec cible et responsable."},
        ],
    },
    {
        "code": "a7",
        "label": "§7",
        "full_title": "§7 - Support",
        "weight": 15,
        "position": 7,
        "requirements": [
            {"reference": "7.1-1", "text": "Ressources humaines SMQ identifiees et disponibles."},
            {"reference": "7.1-2", "text": "Infrastructure ESI maintenue (salles, serveurs, intranet, labo)."},
            {"reference": "7.2-1", "text": "Competences requises definies pour chaque role SMQ."},
            {"reference": "7.2-2", "text": "Ecarts de competences identifies et formation planifiee."},
            {"reference": "7.3-1", "text": "Personnel sensibilise a la demarche qualite ISO 9001."},
            {"reference": "7.5-1", "text": "Documents identifies, approuves et maitrises."},
            {"reference": "7.5-2", "text": "Versioning maitrise et versions obsoletes retirees."},
            {"reference": "7.5-3", "text": "Enregistrements conserves avec durees definies."},
        ],
    },
    {
        "code": "a8",
        "label": "§8",
        "full_title": "§8 - Realisation",
        "weight": 20,
        "position": 8,
        "requirements": [
            {"reference": "8.1-1", "text": "Processus pedagogiques planifies (calendriers, maquettes validees)."},
            {"reference": "8.2-1", "text": "Exigences formations definies (referentiels MESRS, prerequis, competences visees)."},
            {"reference": "8.2-2", "text": "Exigences legales LMD respectees (accreditation, habilitation)."},
            {"reference": "8.3-1", "text": "Conception des programmes pedagogiques formalisee."},
            {"reference": "8.5-1", "text": "Processus operationnels maitrises (inscriptions, examens, stages)."},
            {"reference": "8.5-2", "text": "Enregistrements operationnels crees et conserves."},
            {"reference": "8.6-1", "text": "Criteres de validation etudiants definis et appliques de facon coherente."},
        ],
    },
    {
        "code": "a9",
        "label": "§9",
        "full_title": "§9 - Evaluation",
        "weight": 15,
        "position": 9,
        "requirements": [
            {"reference": "9.1-1", "text": "KPI definis par processus (reussite, delais, placement, etc.)."},
            {"reference": "9.1-2", "text": "Valeurs KPI collectees regulierement selon la frequence definie."},
            {"reference": "9.1-3", "text": "Resultats KPI analyses pour detecter les derives."},
            {"reference": "9.2-1", "text": "Programme annuel d'audits internes etabli."},
            {"reference": "9.2-2", "text": "Auditeurs selectionnes selon independance et competence."},
            {"reference": "9.2-3", "text": "Rapports d'audit rediges et non-conformites saisies."},
            {"reference": "9.3-1", "text": "Revue de direction formelle organisee avec proces-verbal."},
            {"reference": "9.3-2", "text": "Decisions de revue documentees avec responsables et delais."},
        ],
    },
    {
        "code": "a10",
        "label": "§10",
        "full_title": "§10 - Amelioration",
        "weight": 10,
        "position": 10,
        "requirements": [
            {"reference": "10.2-1", "text": "Non-conformites documentees avec cause et service concerne."},
            {"reference": "10.2-2", "text": "Analyse des causes racines effectuee."},
            {"reference": "10.2-3", "text": "Actions correctives definies, mises en oeuvre et verifiees."},
            {"reference": "10.3-1", "text": "Amelioration continue demontree dans le temps."},
            {"reference": "10.3-2", "text": "Bonnes pratiques capitalisees et partagees en interne."},
        ],
    },
]

