# Generated by Django 5.1.4 on 2026-05-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_utilisateursettings_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('TACHE_AFFECTEE', 'Tâche affectée'), ('TACHE_MODIFIEE', 'Tâche modifiée'), ('TACHE_DEMARREE', 'Tâche démarrée'), ('TACHE_TERMINEE', 'Tâche terminée'), ('TACHE_ANNULEE', 'Tâche annulée'), ('TACHE_RETARD', 'Tâche en retard')], max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(db_column='id_destinataire', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.utilisateur')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
