# Generated by Django 5.1.15 on 2026-05-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('TACHE_AFFECTEE', 'Tâche affectée'), ('TACHE_MODIFIEE', 'Tâche modifiée'), ('TACHE_DEMARREE', 'Tâche démarrée'), ('TACHE_TERMINEE', 'Tâche terminée'), ('TACHE_ANNULEE', 'Tâche annulée'), ('TACHE_RETARD', 'Tâche en retard'), ('PV_CREE', 'PV créé'), ('SOUMISSION_FICHE', 'Soumission de fiche'), ('AUDIT_FICHE_EN_COURS', "Fiche en cours d'audit"), ('AUDIT_CORRECTION_DEMANDEE', 'Correction demandée'), ('AUDIT_FICHE_PUBLIEE', 'Fiche publiée')], max_length=50),
        ),
    ]
