# Generated by Django 5.1.4 on 2026-05-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TachePlanifiee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_tache', models.CharField(choices=[('Audit', 'Audit'), ('Documentation', 'Documentation'), ('Validation', 'Validation'), ('Correction', 'Correction'), ('Réunion', 'Réunion'), ('Formation', 'Formation'), ('Autre', 'Autre')], max_length=50)),
                ('responsable', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('priorite', models.CharField(choices=[('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Basse', 'Basse')], default='Moyenne', max_length=20)),
                ('statut', models.CharField(choices=[('Planifiée', 'Planifiée'), ('En cours', 'En cours'), ('Terminée', 'Terminée'), ('Annulée', 'Annulée')], default='Planifiée', max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tache_planifiee',
                'ordering': ['-created_at'],
            },
        ),
    ]
