# Generated by Django 5.1.4 on 2026-05-09 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tacheplanifiee',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
