# Generated by Django 5.1.15 on 2026-05-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='PV Code')),
                ('type', models.CharField(choices=[('SUIVI', 'Follow-up'), ('REVUE_DG', 'Meeting')], max_length=20, verbose_name='PV Type')),
                ('date', models.DateField(verbose_name='PV Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PV',
                'verbose_name_plural': 'PVs',
                'db_table': 'pv',
                'ordering': ['-date', '-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PVParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'pv_participants',
                'managed': False,
            },
        ),
    ]
