# Generated by Django 5.1.15 on 2026-05-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTerrain',
            fields=[
                ('id_audit_field', models.AutoField(primary_key=True, serialize=False)),
                ('date_audit', models.DateField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_field',
                'managed': False,
            },
        ),
    ]
