# Generated by Codex for the settings feature.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_departement_alter_user_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtilisateurSettings",
            fields=[
                (
                    "utilisateur",
                    models.OneToOneField(
                        db_column="id_user",
                        db_constraint=False,
                        on_delete=models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to="accounts.utilisateur",
                        to_field="id_user",
                    ),
                ),
                (
                    "photo_profil",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("preferences", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "utilisateur_settings",
            },
        ),
    ]
