# Generated by Django 5.1.15 on 2026-05-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_utilisateursettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateursettings',
            name='utilisateur',
            field=models.OneToOneField(db_column='id_user', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='accounts.utilisateur'),
        ),
    ]
