# Generated by Django 5.1.15 on 2026-05-09 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
    ]
